---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: loki-s3-logs-ingestor
  namespace: monitoring
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
           - name: loki-s3-logs-ingestor
             image: harshalk91/loki-s3-logs-ingestor
             imagePullPolicy: IfNotPresent
             command: ["python3","loki.py"]
             env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-secret
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-secret
                    key: AWS_SECRET_ACCESS_KEY
          restartPolicy: OnFailure