version: 2.1
executors:
  infra-agent:
    docker:
      - image: zenika/terraform-aws-cli:latest
  python:
    docker:
      - image: docker
jobs:
  plan:
    executor: infra-agent
    steps:
      - checkout
      - run:
          name: terraform plan
          command: cd terraform && terraform init && terraform plan
  apply:
    executor: infra-agent
    steps:
      - checkout
      - run:
          name: terraform apply
          command: cd terraform && terraform init && terraform apply -auto-approve

  push_to_ecr:
    executor: python
    steps:
      - checkout
      - run:
          name: install git and tun
          command: apk add --no-cache python3 py3-pip git && pip3 install --upgrade pip && pip3 install --no-cache-dir awscli && rm -rf /var/cache/apk/* && cd scripts && pip3 install -r requirements.txt

workflows:
  infrastructure:
    jobs:
      - plan:
          context: demo
      - approval-gate:
          type: approval
          requires:
            - plan
      - apply:
          context: demo
          requires:
            - approval-gate

  ecr:
    jobs:
      - push_to_ecr:
          context: demo