version: 2.1
executors:
  infra-agent:
    docker:
      - image: zenika/terraform-aws-cli:latest
  python:
    docker:
      - image: python:alpine
jobs:
  plan:
    executor: infra-agent
    steps:
      - checkout
      - run:
          name: terraform plan
          command: cd terraform && terraform init && terraform plan
  apply:
    executor: infra-agent
    steps:
      - checkout
      - run:
          name: terraform apply
          command: cd terraform && terraform init && terraform apply -auto-approve

  push_to_ecr:
    executor: python
    steps:
      - checkout
      - run:
          name: Build and push image to ecr
          command: cd scripts && pip3 install -r requirements.txt && python3 upload_image.py

workflows:
  infrastructure:
    jobs:
      - plan:
          context: demo
      - approval-gate:
          type: approval
          requires:
            - plan
      - apply:
          context: demo
          requires:
            - approval-gate

  ecr:
    jobs:
      - approval-gate:
          type: approval
      - push_to_ecr:
          context: demo
          requires:
            - approval-gate