version: 2.1
executors:
  infra-agent:
    docker:
      - image: zenika/terraform-aws-cli:latest
jobs:
  plan:
    executor: infra-agent
    working_directory: ~/project/terraform
    steps:
      - checkout
      - run:
          name: terraform plan
          command: terraform init && terraform plan
  apply:
    executor: infra-agent
    working_directory: ~/project/terraform
    steps:
      - checkout
      - run:
          name: terraform apply
          command: terraform init && terraform apply

workflows:
  infrastructure:
    jobs:
      - plan:
          context: demo
      - approval-gate:
          type: approval
          requires:
            - plan
      - apply:
          context: demo
          requires:
            - approval-gate